#!/usr/bin/env node
/**
 * Seed-SQL generator for the inaugural Kamala retreat.
 *
 * This script does NOT touch the database. It prints a single block of
 * idempotent-ish SQL to stdout that can be piped into:
 *
 *   node scripts/seed.mjs > drizzle/seed.sql
 *   wrangler d1 execute kamala --local  --file=drizzle/seed.sql
 *   wrangler d1 execute kamala --remote --file=drizzle/seed.sql
 *
 * Notes
 * -----
 * - The schema migration must be applied first (see docs/db.md).
 * - All money is in pence. Prices are taken from docs/brand-context.md.
 * - The Airbnb estate address is intentionally omitted (`tbc_address = 1`)
 *   until Holly confirms the listing booking. Lat/lng are placeholder zeros.
 * - Sound healing + cacao/reishi practitioners are still TBC; the row is
 *   created with `is_tbc = 1` but only one TBC slot is seeded for clarity.
 * - Year of inaugural weekend is 2026 (per project_decisions.md).
 *
 * Re-running
 * ----------
 * The INSERTs use `INSERT OR IGNORE` keyed on the relevant unique indexes
 * (location.slug, retreat.slug, practitioner.slug, room_types.(retreat_id,
 * code), add_ons.(retreat_id, code)) so re-running is safe but will not
 * mutate existing rows.
 */

// ---- Reference values ---------------------------------------------------

// Friday 7pm London → Sunday 3pm London, 2-4 October 2026.
// London is BST (UTC+1) on those dates.
//  Fri 2026-10-02 19:00 BST = 2026-10-02 18:00 UTC = epoch 1790964000
//  Sun 2026-10-04 15:00 BST = 2026-10-04 14:00 UTC = epoch 1791122400
const STARTS_AT = Math.floor(Date.UTC(2026, 9, 2, 18, 0, 0) / 1000); // 2026-10-02T18:00:00Z
const ENDS_AT = Math.floor(Date.UTC(2026, 9, 4, 14, 0, 0) / 1000); // 2026-10-04T14:00:00Z

const LOCATION_SLUG = 'inaugural-private-estate-uk';
const RETREAT_SLUG = 'kamala-inaugural-weekend-october-2026';

const ROOM_TYPES = [
  {
    code: 'standard',
    name: 'Standard',
    description: 'Beautifully appointed, shared bathroom on the same floor.',
    price_pair_pence: 250000, // £2,500
    price_solo_pence: 225000, // £2,250
    inventory_total: 2,
    sort_order: 10,
  },
  {
    code: 'premium',
    name: 'Premium (en suite)',
    description: 'Larger room with private en suite bathroom.',
    price_pair_pence: 270000, // £2,700
    price_solo_pence: 245000, // £2,450
    inventory_total: 2,
    sort_order: 20,
  },
  {
    code: 'master',
    name: 'Master Suite',
    description: 'The estate flagship — first-come, first-served.',
    price_pair_pence: 300000, // £3,000
    price_solo_pence: 275000, // £2,750
    inventory_total: 2,
    sort_order: 30,
  },
];

const ADD_ONS = [
  {
    code: 'in_room_massage',
    name: 'In-room massage',
    description:
      'Restorative in-room massage delivered on Sunday during free time.',
    unit_price_pence: 10000, // £100 per person
    sort_order: 10,
  },
];

const PRACTITIONERS = [
  {
    slug: 'lacey-shakti',
    name: 'Lacey Shakti',
    discipline: 'Gong & Kundalini Yoga',
    bio: 'Leads our opening gong meditation and kundalini practice.',
    instagram_url: 'https://www.instagram.com/laceywutopia',
    website_url: null,
    is_tbc: 0,
    role: 'Opening gong meditation, kundalini',
    sort_order: 10,
  },
  {
    slug: 'phoenix-breathwork-method',
    name: 'Phoenix Breathwork Method',
    discipline: 'Somatic Energy & Breathwork',
    bio: 'Holds the Saturday afternoon energy release workshop.',
    instagram_url: null,
    website_url: 'https://phoenixbreathworkmethod.com/',
    is_tbc: 0,
    role: 'Saturday energy release workshop',
    sort_order: 20,
  },
  {
    slug: 'sound-healing-tbc',
    name: 'Sound Healing (TBC)',
    discipline: 'Sound Healing',
    bio: 'Sunday pool floating sound healing — practitioner to be confirmed.',
    instagram_url: null,
    website_url: null,
    is_tbc: 1,
    role: 'Sunday pool floating sound healing',
    sort_order: 30,
  },
];

// ---- SQL helpers --------------------------------------------------------

/** Quote a string literal, SQLite-style (single quotes, '' escaping). */
function s(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}
function n(value) {
  if (value === null || value === undefined) return 'NULL';
  return Number(value).toString();
}

// ---- SQL output ---------------------------------------------------------

const lines = [];
lines.push('-- Seed data for the inaugural Kamala retreat.');
lines.push('-- Generated by scripts/seed.mjs — do not hand-edit.');
lines.push('-- Apply only AFTER running drizzle migrations.');
lines.push('');
lines.push('BEGIN TRANSACTION;');
lines.push('');

// Location
lines.push('-- Location: inaugural private estate (address TBC).');
lines.push(
  `INSERT OR IGNORE INTO locations (slug, name, summary, country, region, address, tbc_address, listing_url, lat, lng) VALUES (`,
);
lines.push(
  `  ${s(LOCATION_SLUG)}, ${s('Private Estate (UK)')}, ${s(
    'Exclusive private estate hosting the inaugural Kamala weekend.',
  )}, ${s('United Kingdom')}, NULL, NULL, 1, ${s(
    'https://www.airbnb.co.uk/rooms/1547678291447157775',
  )}, NULL, NULL`,
);
lines.push(');');
lines.push('');

// Retreat
lines.push('-- Retreat: KAMALA Inaugural Weekend, 2-4 October 2026.');
lines.push(
  `INSERT OR IGNORE INTO retreats (slug, name, location_id, tagline, description, starts_at, ends_at, timezone, currency, is_published, is_sold_out) VALUES (`,
);
lines.push(
  `  ${s(RETREAT_SLUG)}, ${s('KAMALA Inaugural Weekend')}, (SELECT id FROM locations WHERE slug = ${s(LOCATION_SLUG)}), ${s(
    'Two nights to rise, reset, and glow.',
  )}, ${s(
    'The first KAMALA retreat — a weekend of rituals, somatic release, breathwork and sound, hosted on a private UK estate.',
  )}, ${n(STARTS_AT)}, ${n(ENDS_AT)}, ${s('Europe/London')}, ${s('GBP')}, 1, 0`,
);
lines.push(');');
lines.push('');

// Room types
lines.push('-- Room types (2 inventory each, prices in pence).');
for (const r of ROOM_TYPES) {
  lines.push(
    `INSERT OR IGNORE INTO room_types (retreat_id, code, name, description, price_pair_pence, price_solo_pence, inventory_total, sort_order) VALUES (`,
  );
  lines.push(
    `  (SELECT id FROM retreats WHERE slug = ${s(RETREAT_SLUG)}), ${s(r.code)}, ${s(r.name)}, ${s(r.description)}, ${n(
      r.price_pair_pence,
    )}, ${n(r.price_solo_pence)}, ${n(r.inventory_total)}, ${n(r.sort_order)}`,
  );
  lines.push(');');
}
lines.push('');

// Add-ons
lines.push('-- Add-ons.');
for (const a of ADD_ONS) {
  lines.push(
    `INSERT OR IGNORE INTO add_ons (retreat_id, code, name, description, unit_price_pence, is_active, sort_order) VALUES (`,
  );
  lines.push(
    `  (SELECT id FROM retreats WHERE slug = ${s(RETREAT_SLUG)}), ${s(a.code)}, ${s(a.name)}, ${s(a.description)}, ${n(
      a.unit_price_pence,
    )}, 1, ${n(a.sort_order)}`,
  );
  lines.push(');');
}
lines.push('');

// Practitioners
lines.push('-- Practitioners + retreat join.');
for (const p of PRACTITIONERS) {
  lines.push(
    `INSERT OR IGNORE INTO practitioners (slug, name, bio, discipline, instagram_url, website_url, is_tbc) VALUES (`,
  );
  lines.push(
    `  ${s(p.slug)}, ${s(p.name)}, ${s(p.bio)}, ${s(p.discipline)}, ${s(p.instagram_url)}, ${s(p.website_url)}, ${n(p.is_tbc)}`,
  );
  lines.push(');');
  lines.push(
    `INSERT OR IGNORE INTO retreat_practitioners (retreat_id, practitioner_id, role, sort_order) VALUES (`,
  );
  lines.push(
    `  (SELECT id FROM retreats WHERE slug = ${s(RETREAT_SLUG)}), (SELECT id FROM practitioners WHERE slug = ${s(p.slug)}), ${s(p.role)}, ${n(p.sort_order)}`,
  );
  lines.push(');');
}
lines.push('');

lines.push('COMMIT;');
lines.push('');

process.stdout.write(lines.join('\n'));
